### PR TITLE
created post request, still have to fix errors

### LINKED ISSUE #35: Update classNames in CSS to be more unique
I suggest having the name of the page in the beginning ex  className="dashboard-container"

### LINKED ISSUE #61: Connect add pet pages to backend

### LINKED ISSUE #70: add mandatory fields to forms

### PR DESCRIPTION
**Pull request by Maarimar**

### CODE REVIEW

**Comment by Count-MonteCristo** [comment]
Once this issue is addressed, the PR ...

- Closes #35
- Closes #61
- Closes #70

File: src/components/pages/AddPet.js [hunk 1]
```diff
@@ -1,192 +1,325 @@
...
+          },
+        });
+
+        console.log("Submitting form .."); // Debug
+
+        if (response.status === 200) {
+          console.log("Success adding pet"); // Debug
+
+          setSuccessMessage("Pet added successfully!");
+          setErrorMessage("");
```
Comment (dkprioleau) [inline src/components/pages/AddPet.js:72]: I think you can just add this when there is an error

File: src/components/pages/AddPet.js [hunk 2]
```diff
@@ -1,192 +1,325 @@
...
+          setPetColor("");
+          setPetGender("");
+          setPetLocation("");
+          setPetDate("");
+          setPetDescription("");
+        }
+      } catch (error) {
+        console.error("Error:", error); // Debug
+
+        setSuccessMessage("");
```
Comment (dkprioleau) [inline src/components/pages/AddPet.js:89]: same thing as above

File: src/components/pages/AddPet.js [hunk 3]
```diff
@@ -1,192 +1,325 @@
...
+                  placeholder="Zip code"
+                  value={petLocation}
+                  onChange={handleInputChange}
+                />
+              </FormGroup>
+            </Col>
+            <br></br>
+            <Col>
+              <FormGroup>
+                <Label for="dateLost">Date Lost</Label>
```
Comment (dkprioleau) [inline src/components/pages/AddPet.js]: don't forget to change this depending if lost or found

File: src/components/pages/AddPet.js (hunk 1 above)
Comment (dkprioleau) [reply src/components/pages/AddPet.js:72]: Also it would be great if you styled the notification message similar to the notification message for the login page

File: src/components/pages/AddPet.js [hunk 4]
```diff
@@ -1,192 +1,325 @@
...
-    petName: "",
-    animalType: "",
-    breed: "",
-    color: "",
-    sex: "",
-    location: "",
-    dateFound: "",
-    description: "",
-  };
+import { useState, useEffect } from "react";
```
Comment (dkprioleau) [inline src/components/pages/AddPet.js]: remove useEffect if not in use

**Review by dkprioleau — COMMENTED** [review]
You can place in draft if you're still fixing errors

**Review by jamisonvalentine — APPROVED** [review]
